"""remove unique constraint on station_code

Revision ID: 5a39620b99fc
Revises: e076a8b3f26c
Create Date: 2025-04-06 19:40:32.355212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a39620b99fc'
down_revision = 'e076a8b3f26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_times', schema=None) as batch_op:
        batch_op.drop_constraint('station_times_station_code_key', type_='unique')

    with op.batch_alter_table('station_waves', schema=None) as batch_op:
        batch_op.drop_constraint('station_waves_station_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_waves', schema=None) as batch_op:
        batch_op.create_unique_constraint('station_waves_station_code_key', ['station_code'])

    with op.batch_alter_table('station_times', schema=None) as batch_op:
        batch_op.create_unique_constraint('station_times_station_code_key', ['station_code'])

    # ### end Alembic commands ###
