networks:
  nginx-manager_customnetwork:
    external: true

services:
  guncang-zookeeper:
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.90
    restart: always
    image: confluentinc/cp-zookeeper
    container_name: guncang-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
    ports:
      - "2183:2183"

  guncang-kafka:
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.91
    restart: always
    container_name: guncang-kafka
    image: confluentinc/cp-kafka
    depends_on:
      - guncang-zookeeper
    ports:
      - "9093:9093"
      - "9201:9201"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "172.20.0.90:2183"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9093,OUTSIDE://0.0.0.0:9201"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://172.20.0.91:9093,OUTSIDE://85.209.163.202:9201"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  guncang-kafka-2:
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.92
    restart: always
    container_name: guncang-kafka-2
    image: confluentinc/cp-kafka
    depends_on:
      - guncang-zookeeper
    ports:
      - "9202:9202"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "172.20.0.90:2183"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9093,OUTSIDE://0.0.0.0:9202"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://172.20.0.92:9093,OUTSIDE://85.209.163.202:9202"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  guncang-kafka-3:
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.93
    restart: always
    container_name: guncang-kafka-3
    image: confluentinc/cp-kafka
    depends_on:
      - guncang-zookeeper
    ports:
      - "9203:9203"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "172.20.0.90:2183"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9093,OUTSIDE://0.0.0.0:9203"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://172.20.0.93:9093,OUTSIDE://85.209.163.202:9203"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  guncang-kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: guncang-kafdrop
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.94
    depends_on:
      - guncang-kafka
      - guncang-kafka-2
      - guncang-kafka-3
    ports:
      - "9204:9204"
    environment:
      KAFKA_BROKERCONNECT: "172.20.0.91:9093,172.20.0.92:9093,172.20.0.93:9093"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_PORT: 9204

  guncang-timescale:
    image: timescale/timescaledb:latest-pg15
    container_name: guncang-timescale
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.95
    command: ["-p", "9205"]
    environment:
      - POSTGRES_USER=guncang
      - POSTGRES_PASSWORD=guncang
      - POSTGRES_DB=ml_db
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=timescaledb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9205:9205"

  guncang-redis:
    image: redis
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.96
    container_name: guncang-redis
    command: ["redis-server", "--port", "9206"]
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "9206:9206"

  guncang-seedlink:
    pull_policy: "always"
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.97
    restart: always
    depends_on:
      - guncang-kafka
      - guncang-kafka-2
      - guncang-kafka-3
    image: docker.io/slackingdjaeger/guncang-seedlink:latest
    container_name: guncang-seedlink
    ports:
      - "9207:5000"

  guncang-migrations:
    image: docker.io/slackingdjaeger/guncang-machine-learning:latest
    container_name: guncang-migrations
    command: flask db upgrade
    restart: "no"
    depends_on:
      - guncang-timescale
    networks:
      - nginx-manager_customnetwork

  guncang-picker:
    pull_policy: "always"
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.98
    restart: always
    depends_on:
      - guncang-kafka
      - guncang-kafka-2
      - guncang-kafka-3
      - guncang-timescale
      - guncang-seedlink
    image: docker.io/slackingdjaeger/guncang-picker:latest
    container_name: guncang-picker

  guncang-machine-learning-1:
    image: docker.io/slackingdjaeger/guncang-machine-learning:latest
    container_name: guncang-machine-learning-1
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.99
    restart: always
    depends_on:
      - guncang-redis
      - guncang-timescale
      - guncang-picker
    ports:
      - "9208:5001"

  guncang-machine-learning-2:
    image: docker.io/slackingdjaeger/guncang-machine-learning:latest
    container_name: guncang-machine-learning-2
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.100
    restart: always
    depends_on:
      - guncang-redis
      - guncang-timescale
      - guncang-picker
    ports:
      - "9209:5001"

  guncang-machine-learning-3:
    image: docker.io/slackingdjaeger/guncang-machine-learning:latest
    container_name: guncang-machine-learning-3
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.101
    restart: always
    depends_on:
      - guncang-redis
      - guncang-timescale
      - guncang-picker
    ports:
      - "9210:5001"

  guncang-ml-nginx:
    image: nginx:latest
    container_name: guncang-ml-nginx
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.102
    ports:
      - "9211:80"
    volumes:
      - ./nginx-ml.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - guncang-machine-learning-1
      - guncang-machine-learning-2
      - guncang-machine-learning-3
    restart: always

  guncang-server:
    image: docker.io/slackingdjaeger/guncang-server:latest
    container_name: guncang-server
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.103
    restart: always
    depends_on:
      - guncang-kafka
      - guncang-kafka-2
      - guncang-kafka-3
      - guncang-timescale
      - guncang-picker
    ports:
      - "9212:8080"

volumes:
  postgres_data:
  redis_data:
