networks:
  nginx-manager_customnetwork:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  new-eews-postgres:
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.56
    restart: always
    image: postgres:13
    container_name: new-eews-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  new-eews-redis:
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.58
    restart: always
    image: redis
    container_name: new-eews-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
