services:
  db:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ml_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ml-service:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ml_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    command: ["python", "-c", "from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all(); app.run(host='0.0.0.0', port=5001, debug=True)"]

volumes:
  postgres_data:
  redis_data:

