services:
  db:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ml_db
  redis:
    image: redis
    ports:
      - "6379:6379"

