services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seismic
    volumes:
      - timescale-data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=timescaledb
volumes:
  timescale-data:
