name: Deploy Machine Learning

on:
  push:
    branches:
      - main
    paths:
      - "docker/docker-compose.build-machine-learning.yaml"
      - "machine-learning/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env
        run: |
          cat <<EOF > seedlinkclient/.env
          FLASK_APP=${{ secrets.FLASK_APP }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}/ml_db
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.SEEDLINK_REDIS_PORT }}
          EOF

      - name: Build and push images
        run: |
          docker compose -f docker/docker-compose.build-machine-learning.yaml build --push
