name: Deploy EEWS New Architecture

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      kafka_changed: \${{ steps.file-changed.outputs.kafka_changed }}
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changed files
        id: file-changed
        run: |
          git fetch origin main --depth=1
          echo "kafka_changed=\$(git diff --quiet origin/main -- docker-config/docker-compose.kafka.yaml || echo 'true')" >> \$GITHUB_OUTPUT

  deploy-kafka:
    needs: setup
    if: ${{ setup.outputs.kafka_changed == 'true' }}
    uses: ./.github/workflows/deploy-kafka.yml